apiVersion: v1
kind: ServiceAccount
metadata:
  name: vkube-backend
  namespace: vkube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vkube-backend-cluster-admin
subjects:
  - kind: ServiceAccount
    name: vkube-backend
    namespace: vkube
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
